# Generated by Django 4.2.2 on 2023-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_buyer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pin',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
